#!/bin/bash

source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
sudo aptitude update -y
sudo aptitude install rethinkdb -y
sudo aptitude install g++ -y

cd /tmp
wget https://nodejs.org/dist/v4.1.2/node-v4.1.2.tar.xz
tar -xzf node-v4.1.2.tar.gz
cd node-v4.1.2
./configure
sudo make install
